version: '3'

services:
  drawio:
    image: jgraph/drawio:${DRAWIO_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    networks:
      - drawio
    ports:
      - 8080:8080
      - 8443:8443

networks:
  drawio:
