version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_VERSION:-latest}
    command:
      - start
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - ${KC_APP_ROOT:-/opt/persistent-storage/keycloak/app}/themes:/opt/keycloak/themes
      - ${KC_APP_ROOT:-/opt/persistent-storage/keycloak/app}/x509:/etc/x509/https
    networks:
      - keycloak
    ports:
      - ${KC_HTTPS_PORT:-8443}:${KC_HTTPS_PORT:-8443}
    depends_on:
      - postgres
  postgres:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_VERSION:-14}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${POSTGRES_APP_ROOT:-/opt/persistent-storage/keycloak/postgres}:/var/lib/postgresql/data
    networks:
      - keycloak

networks:
  keycloak:
