version: '3'

services:
  sftpgo:
    image: drakkan/sftpgo:${SFTPGO_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - ${SFTPGO_APP_ROOT:-/opt/persistent-storage/sftpgo/app}:/var/lib/sftpgo
      - ${SFTPGO_DATA_ROOT:-/opt/persistent-storage/sftpgo/app}:/srv/sftpgo/data
      - type: bind
        source: ${SFTPGO_SHARED_ROOT:-/opt/persistent-storage/sftpgo/shared_area}
        target: /mnt/shared_area
    networks:
      - sftpgo
    ports:
      - ${SFTPGO_HTTP_PORT:-8080}:8080
      - ${SFTPGO_SSH_PORT:-8080}:2022

networks:
  sftpgo:
    enable_ipv6: true
