version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - ${FORGEJO_APP_ROOT:-/opt/persistent-storage/jellyfin/app}/config:/config
      - ${FORGEJO_APP_ROOT:-/opt/persistent-storage/jellyfin/app}/cache:/cache
      - ${FORGEJO_MEDIA_ROOT:-/opt/persistent-storage/jellyfin/media}:/mnt/media
    networks:
      - jellyfin
    ports:
      - 8096:8096
      - 7359:7359/udp

networks:
  jellyfin:
