version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_VERSION:-latest}
    restart: unless-stopped
    env_file: .env
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    volumes:
      - ${JELLYFIN_APP_ROOT:-/opt/persistent-storage/jellyfin/app}/config:/config
      - ${JELLYFIN_APP_ROOT:-/opt/persistent-storage/jellyfin/app}/cache:/cache
      - type: bind
        source: ${JELLYFIN_MEDIA_ROOT:-/opt/persistent-storage/jellyfin/media}
        target: /multimedia
    networks:
      - jellyfin
    ports:
      - ${JELLYFIN_HTTP_PORT:-8096}:8096
      - ${JELLYFIN_DISCOVERY_PORT:-7359}:7359/udp

networks:
  jellyfin:
